language: php

php:
    - 5.4
    - 5.5
    - 5.6

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer install --no-interaction --prefer-dist

before_install:
    - travis_retry composer self-update
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
    - mysql -u root -e 'CREATE SCHEMA `yii` CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL ON `yii`.* TO test@localhost IDENTIFIED BY "test"; FLUSH PRIVILEGES;'

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
